#!/usr/bin/python3
def raise_exception_msg(message=""):
    try:
        almah = 1
        print(alma)
        raise_exception_msg("C is fun")
    except NameError as ne:
        print(ne)
